apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-watch-event-cronjob
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes (you can adjust this cron schedule)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: k8s-watch-event
              image: <your-docker-registry>/k8s-watch-event:latest
              env:
                - name: SLACK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack-secrets
                      key: SLACK_TOKEN
          restartPolicy: OnFailure
